services:
  - type: web
    name: library-management-api
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    plan: free
    envVars:
      - key: APP_NAME
        value: LibraryManagementAPI
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: library-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: library-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: library-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: library-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: library-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_DRIVER
        value: sync

databases:
  - name: library-db
    databaseName: library_db
    user: library_user
    plan: free